import { Rajdhani } from "next/font/google";
import "./globals.css";
import Header from "./_Components/Header/Header";
import Footer from "./_Components/Footer/Footer";
import AuthProvider from "./Services/AuthProvider/AuthProvider";

const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export const metadata = {
  title: "Orfarm Grocery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
