import { Rajdhani } from "next/font/google";
import "./globals.css";
import Header from "./_Components/Header/Header";
import Footer from "./_Components/Footer/Footer";
import AuthProvider from "./Services/AuthProvider/AuthProvider";
import { Toaster } from "react-hot-toast";
import ProviderQuery from "./ProviderQuery";
import ProductProvider from "./Services/ProductProvider/ProductProvider";
import ReduxProvider from "./ReduxProvider/ReduxProvider";
const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export const metadata = {
  title: "Orfarm Grocery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <ReduxProvider>
          <ProviderQuery>
            <AuthProvider>
              <ProductProvider>
                <Header />
                {children}
                <Footer />
                <Toaster />
              </ProductProvider>
            </AuthProvider>
            <Toaster />
          </ProviderQuery>
        </ReduxProvider>
      </body>
    </html>
  );
}
